run percy on label; ignore drafts

diff --git a/.github/workflows/pr-percy-snapshots.yml b/.github/workflows/pr-percy-snapshots.yml
--- a/.github/workflows/pr-percy-snapshots.yml
+++ b/.github/workflows/pr-percy-snapshots.yml
@@ -58,6 +58,30 @@ jobs:
           commitsh: ${{ steps.get_pr_data.outputs.sha }}
           percy_token_write: ${{ secrets.PERCY_TOKEN_WRITE }}
 
+  remove_percy_label:
+    name: Remove Percy test requested label
+    needs: upload
+    # Run on success or failure; that way if the build fails for some reason the label is still removed
+    # This works as long as the get_pr_data step has succeeded, as it needs the PR number. 
+    if: ${{ needs.upload.outputs.pr_number != '' }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: URL-encode label data for API request
+        id: url_encode
+        run: |
+          set -e
+          test_requested_label_name=$(echo -n "${{ vars.PERCY_TEST_REQUESTED_LABEL_NAME }}" | jq -s -R -r @uri)
+          echo "test_requested_label_name=$test_requested_label_name" >> $GITHUB_OUTPUT
+          
+      - name: Remove ${{ vars.PERCY_TEST_REQUESTED_LABEL_NAME }} label
+        uses: octokit/request-action@v2.x
+        with:
+          route: "DELETE /repos/${{ github.repository }}/issues/${{ needs.upload.outputs.pr_number }}/labels/${{ steps.url_encode.outputs.test_requested_label_name }}"
+          owner: octokit
+          repo: request-action
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
   # Add a check to the PR to show that screenshots were sent to Percy
   # Manual status check to be removed once IS-GHA integration is complete
   # https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run
